# -*- coding: utf-8 -*-
"""instagram.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r3RGhUVFzNRoFHuUcc2FYPbbZ6sAgzT3
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
plt.style.use('ggplot')

users = pd.read_csv('/content/users.csv')
photos = pd.read_csv('/content/photos.csv')
likes = pd.read_csv('/content/likes.csv')
comments = pd.read_csv('/content/comments.csv')
tags = pd.read_csv('/content/tags.csv')
photo_tags = pd.read_csv('/content/photo_tags.csv')
follows = pd.read_csv('/content/follows.csv')

print("Users Shape:", users.shape)
print("Photos Shape:", photos.shape)
print("Likes Shape:", likes.shape)
print("Comments Shape:", comments.shape)
print("Tags Shape:", tags.shape)
print("Photo Tags Shape:", photo_tags.shape)
print("Follows Shape:", follows.shape)

print(users.head())
print(photos.head())

likes_per_photo = likes.groupby('photo').size().reset_index(name='likes_count')

likes_per_photo.head()

comments_per_photo = comments.groupby('Photo id').size().reset_index(name='comments_count')

comments_per_photo.head()

engagement = photos.merge(
    likes_per_photo,
    left_on='id',
    right_on='photo', # Corrected column name
    how='left'
)

engagement = engagement.merge(
    comments_per_photo,
    left_on='id',
    right_on='Photo id', # Corrected column name
    how='left'
)

engagement['likes_count'] = engagement['likes_count'].fillna(0)
engagement['comments_count'] = engagement['comments_count'].fillna(0)

engagement.head()

engagement['total_engagement'] = (
    engagement['likes_count'] +
    engagement['comments_count']
)

engagement[['id','likes_count','comments_count','total_engagement']].head()

engagement['created_at'] = pd.to_datetime(
    engagement['created dat'], dayfirst=True
)

engagement['hour'] = engagement['created_at'].dt.hour
engagement['day'] = engagement['created_at'].dt.day_name()

engagement.head()

hourly_engagement = engagement.groupby(
    'hour'
)['total_engagement'].mean()

hourly_engagement

plt.figure(figsize=(10,5))
hourly_engagement.plot(kind='bar')

plt.title('Average Engagement by Hour')
plt.xlabel('Hour')
plt.ylabel('Engagement')

plt.show()

hashtags = photo_tags.merge(
    tags,
    left_on='tag ID',
    right_on='id'
)

hashtags.head()

top_hashtags = hashtags['tag text'].value_counts().head(10)

print(top_hashtags)

plt.figure(figsize=(10,5))

sns.barplot(
    x=top_hashtags.values,
    y=top_hashtags.index
)

plt.title('Top 10 Hashtags')
plt.show()

top_photos = engagement.sort_values(
    by='total_engagement',
    ascending=False
).head(10)

top_photos[['id','total_engagement']]

followers_received = follows.groupby(
    'followee '
).size().reset_index(name='followers')

followers_received.head()

top_followed = followers_received.sort_values(
    by='followers',
    ascending=False
)

top_followed.head(10)

heatmap_data = engagement.pivot_table(
    values='total_engagement',
    index='day',
    columns='hour',
    aggfunc='mean'
)

plt.figure(figsize=(15,6))

sns.heatmap(
    heatmap_data,
    cmap='YlGnBu'
)

plt.title('Engagement Heatmap')
plt.show()

daily_engagement = engagement.groupby('day')['total_engagement'].mean()

best_hour = hourly_engagement.idxmax()
best_day = daily_engagement.idxmax()

print("Best Posting Hour:", best_hour)
print("Best Posting Day:", best_day)

print("Recommended Content Calendar")

print(f"Best Day: {best_day}")
print(f"Best Time: {best_hour}:00")

print("\nStrategies:")

print("1. Post during peak engagement hours.")
print("2. Use top-performing hashtags.")
print("3. Encourage comments with questions.")
print("4. Increase posting frequency on high-engagement days.")
print("5. Collaborate with influencers and active users.")